### ISSUE TITLE
Decouple full scans from incremental scans; types of incrementals

### ISSUE THREAD

**Issue by hexastax** [nsoft/jesterj#11]
It'll be worth decoupling any incremental scan functionality into its own set of interface(s)/class(es).

There are a few things to consider for incrementals:
1. Some systems emit 'events' when their data changes to any 'listeners'; our scanners may be such listeners.
2. The former seems a more rare case, so we have to ascertain the deltas ourselves. That breaks down into two sub-cases:
   - the source system allows you to ask it for deltas
   - the source system doesn't track changes so we need to track them ourselves through e.g. MD5 hashes stored in our internal persistence

**Comment by nsoft** [comment]
Exactly, though it's not clear to me who's going to use these interfaces. Scanners (and steps, and plans) are all active objects that run in their own thread so they are pretty decoupled from the rest of the world. They can pretty much do whatever they want. One could argue that the entire scanner interface is not necessary. It's mostly there as an exposition of what I was thinking about...

**Comment by hexastax** [comment]
The interfaces are for contributors, and for maintaining a common object model. They're also guides for what functionality needs to be there.

**Comment by nsoft** [comment]
#57 addresses this. All scanners should inherit from ScannerImpl which has builder options to turn on "memory" and "change detection" which together amount to support for incremental scans.
