### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#116]
This version (java 10) of java is not currently supported (please use 1.8) Filing this ticket to help folks who run into this and track that it gets fixed when java > 1.8 is supported. The root of the problem is the log4j2.xml file is not found via 

`        InputStream log4jxml = Main.class.getClass().getResourceAsStream("/log4j2.xml");`

probably related to the new module system etc...

**Comment by nsoft** [comment]
More info, recently gave a quick shot at 11...

    WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

which then leads to:
````
java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
	at org.jesterj.ingest.Main.lambda$main$0(Main.java:148)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-09-18T22:25:41,245 ERROR Thread-1 org.apache.cassandra.service.CassandraDaemon Exception in thread Thread[Thread-1,5,main] java.lang.NullPointerException
	at org.jesterj.ingest.Main.lambda$main$0(Main.java:181)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

This appears to be related to the log4j use of Multi-Release jars

**Comment by nsoft** [comment]
https://stackoverflow.com/questions/53049346/is-log4j2-compatible-with-java-11 for reference

**Comment by nsoft** [comment]
Tried adding Multi-Release:true to the manifest, but probably the problem is that OneJar which was last maintained in 2012/2013 doesn't know anything about MRJars ... ugh

**Comment by nsoft** [comment]
This is in progress and thus far has required upgrading:
Tika --> 1.23
log4j --> 2.13
graphviz --> 0.11.0
easymock --> 4.1
cassandra --> 4.0-Alpha3-SNAPSHOT

The following cassandra issues are critical: 
https://issues.apache.org/jira/browse/CASSANDRA-15494
https://issues.apache.org/jira/browse/CASSANDRA-12995

Also our startup is complicated by https://issues.apache.org/jira/browse/CASSANDRA-15468 in which
the jdk module system for 11 has to have export/opens directives.

Additionally One-Jar was finally formally forked and distributed as Uno-Jar --> 0.99 to fix class loading issues.

**Comment by nsoft** [comment]
The above are resolved and head versions of Cassandra should now work with the project. After some adjustment for the new class name of the JarClassLoader, the plan config class is now found, but Log4J is complaining and later failing because this throws an exception that originates in the call to callerClass(clazz).
```
    public static Logger getLogger(final Class<?> clazz) {
        final Class<?> cls = callerClass(clazz);
        return getContext(cls.getClassLoader(), false).getLogger(toLoggerName(cls));
    }
```
The root of the problem seems to be that in JDK 11 `sun.reflect.Reflection.getCallerClass` isn't supported which hits this catch block:
```
        } catch (final Exception | LinkageError e) {
            System.out.println("WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.");
            getCallerClass = null;
            java7u25CompensationOffset = -1;
        }
        GET_CALLER_CLASS = getCallerClass;
        JDK_7u25_OFFSET = java7u25CompensationOffset;
```
From the printed message it seems we should still be working but with lower performance but with the static final GET_CALLER_CLASS field set to null callerClass(clazz) inevitably hits:

```
        // note that we need to add 1 to the depth value to compensate for this method, but not for the Method.invoke
        // since Reflection.getCallerClass ignores the call to Method.invoke()
        try {
            return (Class<?>) GET_CALLER_CLASS.invoke(null, depth + 1 + JDK_7u25_OFFSET);
        } catch (final Exception e) {
            // theoretically this could happen if the caller class were native code
            // TODO: return Object.class
            return null;
        }
```
Which of course returns null because GET_CALLER_CLASS is null and attempting to call .invoke() throws an exception. The null return bubbles up and causes the UnsupportedOperationException here:
```
   private static Class<?> callerClass(final Class<?> clazz) {
        if (clazz != null) {
            return clazz;
        }
        final Class<?> candidate = StackLocatorUtil.getCallerClass(3);
        if (candidate == null) {
            throw new UnsupportedOperationException("No class provided, and an appropriate one cannot be found.");
        }
        return candidate;
    }
```
And thus all calls to `LogManager.getLogger();` are doomed to throw an exception and fail. To me this seems like a bug because that's quite a bit worse than the expectation set by the message that says "This will impact performance" (as in not run at all?)

Unfortunately though I can work around this for the specific cases in my code for a plan config, dependent libraries  will try to use  `LogManager.getLogger();` and fail. It's not yet clear if this is a bug in log4j or if there is some adjustment for JDK11 I'm not yet making.

**Comment by jvz** [comment]
That class is overwritten for Java 9+: https://github.com/apache/logging-log4j2/blob/release-2.x/log4j-api-java9/src/main/java/org/apache/logging/log4j/util/StackLocator.java

**Comment by nsoft** [comment]
@jvz What does one have to do to get log4j to use the new implementation? 
```
  compile 'org.apache.logging.log4j:log4j-core:2.13.0'
  compile 'org.apache.logging.log4j:log4j-slf4j-impl:2.13.0'
  compile 'org.apache.logging.log4j:log4j-jcl:2.13.0'
  compile 'org.apache.logging.log4j:log4j-1.2-api:2.13.0'
  compile 'org.apache.logging.log4j:log4j-jul:2.13.0'
```
And the stack traces line up perfectly with the downloaded code for 2.13.0 when I analyze them in Intellij

**Comment by nsoft** [comment]
Ah, just realized that the issue is probably this: https://github.com/nsoft/uno-jar/issues/5

**Comment by nsoft** [comment]
Preliminary JDK 11 support is now on a branch here: https://github.com/nsoft/jesterj/tree/jdk11 
This work cannot be merged into main yet as it awaits release of 

Cassandra 4.0.0
Solr 8.5.0
UnoJar 1.0

Also this work has touched and upgraded a lot of dependencies, and the license attributions need to be thoroughly re-checked and updated for the merge. However, anyone less worried about licensing is free to build the branch, build the above libraries/tools (and publish them to their local maven repository) and try it out.

**Comment by nsoft** [comment]
Apache Solr 8.5.0 is out.
UnoJar 1.0 getting close
Cassandra has unfortunately felt the need to do yet another Alpha, not sure when 4.0 will be available, but I may proceed with dependency on their alpha if it takes too long.

**Comment by nsoft** [comment]
merged, still depending on cassandra alpha, but it's in central so it will do for now.
