### ISSUE TITLE
Add class or interface with all common field names

### ISSUE THREAD

**Issue by dgoldenberg1234** [nsoft/jesterj#13]
Rather than us sprinkling the code with string literals it's best if we have a class or interface with the common field names.  This has the advantages of avoiding misspellings and secondly keeping track of what fields we're using.

**Comment by nsoft** [comment]
Going to leave this open so that inspired commits/pull requests can reference it, but I'm not holding up any release for it.

**Comment by nsoft** [comment]
There are several enums for this purpose now. It's a general code cleanup type of thing, and this issue would likely be in "never done" state forever. Specific cleanups can have their own ticket.
