### ISSUE TITLE
Implement XML splitter, XML scanner

### ISSUE THREAD

**Issue by hexastax** [nsoft/jesterj#35]
We see both types of use-cases out there. XML splitter is a common one: split XML using a given XPath which identifies the start of a "document" within the XML DOM.

The other use-case is, one has a large XML file(s) that one wants to treat as a "data source(s)"; so we'll want to have a scanner that reads it and does the same as the XML splitter processor.

**Comment by nsoft** [comment]
Similar to the CSV ticket I think there are two cases, One of discrete whole document processing and one that is continuous or too large for memory processing. The first case should be handled as a DOM based XPath based splitter, The second case would be a StAX scanner similar to the LineByLine scanner except that it takes a particular (xpath like but not full xpath syntax) context and uses that to identify the chunks that are to be turned into documents.

There's also a third posibility, which is a SAX streaming Listener (we haven't done any Listener steps yet, but something has to come first)

So let's split this into 3 tickets:

XPathSplitter implements DocumentProcessor
StAXScanner extends Scanner
SAXInput (?extends scanner, implements Listener?? )

**Comment by hexastax** [comment]
I'm not sure I see the need for both Stax and SAX processors. Why not just Stax?

I feel like we need 4 things:

- XPathSplitter implements DocumentProcessor
- XPathScanner implements Scanner
- StaxSplitter implements DocumentProcessor
- StaxScanner implements Scanner

Since the scanner and the processor for each pair would share some code, I was thinking 2 tickets, one for the DOM-oriented pair and one for the Stax-oriented pair.

What I've also seen in a framework is a splitter which simply lets you configure for the number of the level where the "child" documents are nested.  This is quite limiting but apparently works for a good number of cases.

**Comment by nsoft** [comment]
The stax extractor seems sufficient, If someone needs a dom/xpath version they can contribute in a ticket specific to that implementation
