### ISSUE TITLE
Step for adjusting names of fields

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#4]
Once we have a document in the pipeline we need to be able to adjust the names of fields by regex match replace. For example s/^(file_size)$/$1_i/ to allow dynamic field matching to identify the field as an integer.

**Comment by alwaysreadytolearn** [comment]
Hello @nsoft , I'm new to open source and this project, but I would like to contribute my 2 cents to this project, I feel, fixing this issue might be a good start, what do you think ?

**Comment by nsoft** [comment]
Yup, that's why it's labeled help wanted and up for grabs :)

**Comment by nsoft** [comment]
CopyField processor with removeOriginal can effectively rename a field. Not sure we really need a regex based one.
