### ISSUE TITLE
connection timeout in FetchUrl processor should be configurable

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#60]
Simply need to add a field, and builder param...

**Comment by kaustubhmallik** [comment]
Is this still open. I can take it.

**Comment by nsoft** [comment]
Yup! Fork, fix, pull request... :) TIA!

**Comment by shrikantdange1208** [comment]
Hi,
I guess this issue is still open and I want to work on it. I have forked the repo in intellij. But I can't find any documentation on contributing for this project. Could you please let me know how to setup the project?

**Comment by nsoft** [comment]
Have you seen the [Getting Started](https://github.com/nsoft/jesterj/wiki/Documentation) page on the wiki? If you have further setup questions please join our slack channel where I can answer questions more quickly. Also, that way we can use comments on this issue for questions or decisions specific to resolving this issue.

**Comment by michaelbonadio** [comment]
Looks like nothing has happened here for a while so I will took a stab at this. I think I have something, but do you want the Connection timeout and the read timeout to be set to the same time, or should they be separately configurable?

**Comment by nsoft** [comment]
Separate would be wonderful :)

**Comment by michaelbonadio** [comment]
I believe I have a solution ready. You do not have a issue 60 branch - would you like me to pull request to the master branch, or let you create an issue 60 branch?

**Comment by nsoft** [comment]
pull to master is fine. If it's not suitable, I'll ask you to update your pull request before accepting it.

**Comment by mbiasutto** [comment]
Hi, is this issue still open?

**Comment by nsoft** [comment]
Well apparently it is, but it shouldn't be since I already merged a fix. (closing)
