### ISSUE TITLE
Add details about the need for this product into the documentation page

### ISSUE THREAD

**Issue by santhukumar** [nsoft/jesterj#75]
Write details on why is this product needed and what are the potential use cases this project plans to solve.

Starting point is "we've got a use case that would benefit from using a search engine, but we need to get the data into the search engine" 

As discussed with gus following are the points with added research can be the answer to this issue

1. Primary focus of this project is to provide a very easy to initiate tool for getting data (documents) into search engines.
2.Handle massive data
3. Remove the need for user who is prototyping for customers to have to set up a Hadoop cluster, or a database, or N other ancillary infrastructure elements to get data into the Solr index/ ES index
4. Help folks who have a small amount of data and not a lot of money who could benefit from adding custom search to their site, but can't afford a huge long ETL implementation to get the data into a search engine. Easy to setup and start using would be a very important criterion.
5. If the existing test/database data needs tweaking or changing soon you have massive SQL statements or temp tables, or an ETL process to create the table you actually want... and that doesn't scale well with existing solutions.
6. Can get difficult to handle crashes/massive data during ETL with naive implementations. Make sure those cases are handed well with this product.

@nsoft

**Comment by nsoft** [comment]
Thanks this looks like a good starter for our documentation. I'll try to convert it and add other docs I've been meaning to write sometime this week. Weekend was busy.

**Comment by nsoft** [comment]
Added a FAQ that attempts to capture this information.
