### ISSUE TITLE
Filter scanned files with a glob or regex match

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#78]
The SimpleFileScanner is living up to it's name... it's a bit too simple. It would be nice to be able to specify includes and excludes using either apache ant style file globs or regexes.

**Comment by vigil4j** [comment]
Hi @nsoft
I am new to Open Source but would like to contribute to it. Would I be able to take up this enhancement? If so where do I need to get started? I am good at Java Programming language.
Thanks

**Comment by nsoft** [comment]
Hi @vigil4j 

Welcome! 
Step 1, Read https://github.com/nsoft/jesterj/blob/master/CONTRIBUTING.md 
Step 2, join our slack channel ( you have to send me an email, see https://github.com/nsoft/jesterj for my email... Use slack to ask any additional setup questions)
Step 3, ask further questions about this feature enhancement here on this ticket
