### ISSUE TITLE
Lighter constructors for DocumentImpl, another look at 'rawData'

### ISSUE THREAD

**Issue by hexastax** [nsoft/jesterj#9]
Currently, DocumentImpl's constructor takes a Plan, an Operation, and a Scanner. This seems heavy, especially the last bit since the Scanner is only passed in to get the "sourceScannerName" out.

Should there be a
`DocumentImpl(String id)
DocumentImpl(byte[] rawData, String id)`

It may be worthwhile looking at the rawData as well. How would this accommodate for data that's really large and won't fit into memory?  We'll need something like a 'content pointer' that's a URI pointing to bytes somewhere remote, or 'local' which would amount to a byte[].

**Comment by nsoft** [comment]
#53 addressed this by making it possible to get hold of the key information from an existing document. Generally one should not be making documents from thin air :). Documents particularly need to be able to determine the source scanner. When creating children documents or splitting a document, the constructor in #53 can be used.  Content Pointers can be revisited as it's own ticket when someone wants to contribute code for it.
